package tox

/*
#include <tox/tox.h>
#include <tox/toxav.h>
*/
import "C"

const (
	PUBLIC_KEY_SIZE           = int(C.TOX_PUBLIC_KEY_SIZE)
	SECRET_KEY_SIZE           = int(C.TOX_SECRET_KEY_SIZE)
	ADDRESS_SIZE              = int(C.TOX_ADDRESS_SIZE)
	MAX_NAME_LENGTH           = int(C.TOX_MAX_NAME_LENGTH)
	MAX_STATUS_MESSAGE_LENGTH = int(C.TOX_MAX_STATUS_MESSAGE_LENGTH)
	MAX_FRIEND_REQUEST_LENGTH = int(C.TOX_MAX_FRIEND_REQUEST_LENGTH)
	MAX_MESSAGE_LENGTH        = int(C.TOX_MAX_MESSAGE_LENGTH)
	MAX_CUSTOM_PACKET_SIZE    = int(C.TOX_MAX_CUSTOM_PACKET_SIZE)
	HASH_LENGTH               = int(C.TOX_HASH_LENGTH)
	FILE_ID_LENGTH            = int(C.TOX_FILE_ID_LENGTH)
	MAX_FILENAME_LENGTH       = int(C.TOX_MAX_FILENAME_LENGTH)
)

type UserStatus int

const (
	USER_STATUS_NONE = int(C.TOX_USER_STATUS_NONE)
	USER_STATUS_AWAY = int(C.TOX_USER_STATUS_AWAY)
	USER_STATUS_BUSY = int(C.TOX_USER_STATUS_BUSY)
)

type ConnectionType int

const (
	CONNECTION_NONE = int(C.TOX_CONNECTION_NONE)
	CONNECTION_TCP  = int(C.TOX_CONNECTION_TCP)
	CONNECTION_UDP  = int(C.TOX_CONNECTION_UDP)
)

type FileControlType int

const (
	FILE_CONTROL_RESUME = int(C.TOX_FILE_CONTROL_RESUME)
	FILE_CONTROL_PAUSE  = int(C.TOX_FILE_CONTROL_PAUSE)
	FILE_CONTROL_CANCEL = int(C.TOX_FILE_CONTROL_CANCEL)
)

type FileKind uint32

const (
	FILE_KIND_DATA   = uint32(C.TOX_FILE_KIND_DATA)
	FILE_KIND_AVATAR = uint32(C.TOX_FILE_KIND_AVATAR)
)

type GroupchatType int

const (
	CONFERENCE_TYPE_TEXT = uint8(C.TOX_CONFERENCE_TYPE_TEXT)
	CONFERENCE_TYPE_AV   = uint8(C.TOX_CONFERENCE_TYPE_AV)
)

type CallControlType int

const (
	FRIEND_CALL_STATE_ERROR       = int(C.TOXAV_FRIEND_CALL_STATE_ERROR)
	FRIEND_CALL_STATE_FINISHED    = int(C.TOXAV_FRIEND_CALL_STATE_FINISHED)
	FRIEND_CALL_STATE_SENDING_A   = int(C.TOXAV_FRIEND_CALL_STATE_SENDING_A)
	FRIEND_CALL_STATE_SENDING_V   = int(C.TOXAV_FRIEND_CALL_STATE_SENDING_V)
	FRIEND_CALL_STATE_ACCEPTING_A = int(C.TOXAV_FRIEND_CALL_STATE_ACCEPTING_A)
	FRIEND_CALL_STATE_ACCEPTING_V = int(C.TOXAV_FRIEND_CALL_STATE_ACCEPTING_V)
)

type MessageType int

const (
	MESSAGE_TYPE_NORMAL = int(C.TOX_MESSAGE_TYPE_NORMAL)
	MESSAGE_TYPE_ACTION = int(C.TOX_MESSAGE_TYPE_ACTION)
)

// Group Chat 基础类型
type GroupNumber uint32
type GroupPeerNumber uint32
type GroupMessageId uint64

// Group Chat 枚举类型
type GroupPrivacyState int
type GroupTopicLock int
type GroupVoiceState int
type GroupRole int
type GroupExitType int
type GroupJoinFail int
type GroupModEvent int

// Group 隐私状态
const (
	GROUP_PRIVACY_STATE_PUBLIC  = int(C.TOX_GROUP_PRIVACY_STATE_PUBLIC)
	GROUP_PRIVACY_STATE_PRIVATE = int(C.TOX_GROUP_PRIVACY_STATE_PRIVATE)
)

// Group 话题锁定
const (
	GROUP_TOPIC_LOCK_ENABLED  = int(C.TOX_GROUP_TOPIC_LOCK_ENABLED)
	GROUP_TOPIC_LOCK_DISABLED = int(C.TOX_GROUP_TOPIC_LOCK_DISABLED)
)

// Group 语音状态
const (
	GROUP_VOICE_STATE_ALL       = int(C.TOX_GROUP_VOICE_STATE_ALL)
	GROUP_VOICE_STATE_MODERATOR = int(C.TOX_GROUP_VOICE_STATE_MODERATOR)
	GROUP_VOICE_STATE_FOUNDER   = int(C.TOX_GROUP_VOICE_STATE_FOUNDER)
)

// Group 角色
const (
	GROUP_ROLE_FOUNDER   = int(C.TOX_GROUP_ROLE_FOUNDER)
	GROUP_ROLE_MODERATOR = int(C.TOX_GROUP_ROLE_MODERATOR)
	GROUP_ROLE_USER      = int(C.TOX_GROUP_ROLE_USER)
	GROUP_ROLE_OBSERVER  = int(C.TOX_GROUP_ROLE_OBSERVER)
)

// Group 退出类型
const (
	GROUP_EXIT_TYPE_QUIT           = int(C.TOX_GROUP_EXIT_TYPE_QUIT)
	GROUP_EXIT_TYPE_TIMEOUT        = int(C.TOX_GROUP_EXIT_TYPE_TIMEOUT)
	GROUP_EXIT_TYPE_DISCONNECTED  = int(C.TOX_GROUP_EXIT_TYPE_DISCONNECTED)
	GROUP_EXIT_TYPE_SELF_DISCONNECTED = int(C.TOX_GROUP_EXIT_TYPE_SELF_DISCONNECTED)
	GROUP_EXIT_TYPE_KICK          = int(C.TOX_GROUP_EXIT_TYPE_KICK)
	GROUP_EXIT_TYPE_SYNC_ERROR    = int(C.TOX_GROUP_EXIT_TYPE_SYNC_ERROR)
)

// Group 加入失败类型
const (
	GROUP_JOIN_FAIL_PEER_LIMIT        = int(C.TOX_GROUP_JOIN_FAIL_PEER_LIMIT)
	GROUP_JOIN_FAIL_INVALID_PASSWORD  = int(C.TOX_GROUP_JOIN_FAIL_INVALID_PASSWORD)
	GROUP_JOIN_FAIL_UNKNOWN          = int(C.TOX_GROUP_JOIN_FAIL_UNKNOWN)
)

// Group 管理员事件
const (
	GROUP_MOD_EVENT_KICK         = int(C.TOX_GROUP_MOD_EVENT_KICK)
	GROUP_MOD_EVENT_OBSERVER     = int(C.TOX_GROUP_MOD_EVENT_OBSERVER)
	GROUP_MOD_EVENT_USER         = int(C.TOX_GROUP_MOD_EVENT_USER)
	GROUP_MOD_EVENT_MODERATOR    = int(C.TOX_GROUP_MOD_EVENT_MODERATOR)
)
